### ISSUE TITLE
Incorporate changes from tenside/core for upgrade state

### ISSUE THREAD

**Issue by discordier** [Toflar/composer-resolver#5]
The changes from:
https://github.com/tenside/core/blob/master/src/Task/Composer/UpgradeTask.php#L127
and https://github.com/tenside/core/blob/master/src/Composer/Installer/InstallationManager.php

Need to get pulled in here.

**Comment by Toflar** [comment]
Can you just briefly outline what's stored in `upgrades.json`? Might help for my understanding :)

**Comment by discordier** [comment]
Essentially, it is the same output as in the console when performing a "dry-run" upgrade.
Yet we store a whole lot more details so we can show them in the UI.

The contents look like this example:
```json
    "symfony/symfony": {
        "type": "update",
        "reason": "Required by the root package: Install command rule (install symfony/symfony v3.1.1|install symfony/symfony v2.8.0|install symfony/symfony v2.8.1|install symfony/symfony v2.8.10|install symfony/symfony v2.8.11|install symfony/symfony v2.8.12|install symfony/symfony v2.8.13|install symfony/symfony v2.8.14|install symfony/symfony v2.8.15|install symfony/symfony v2.8.16|install symfony/symfony v2.8.2|install symfony/symfony v2.8.3|install symfony/symfony v2.8.4|install symfony/symfony v2.8.5|install symfony/symfony v2.8.6|install symfony/symfony v2.8.7|install symfony/symfony v2.8.8|install symfony/symfony v2.8.9|install symfony/symfony v3.0.0|install symfony/symfony v3.0.1|install symfony/symfony v3.0.2|install symfony/symfony v3.0.3|install symfony/symfony v3.0.4|install symfony/symfony v3.0.5|install symfony/symfony v3.0.6|install symfony/symfony v3.0.7|install symfony/symfony v3.0.8|install symfony/symfony v3.0.9|install symfony/symfony v3.1.0|install symfony/symfony v3.1.1|install symfony/symfony v3.1.2|install symfony/symfony v3.1.3|install symfony/symfony v3.1.4|install symfony/symfony v3.1.5|install symfony/symfony v3.1.6|install symfony/symfony v3.1.7|install symfony/symfony v3.1.8|install symfony/symfony v3.1.9|install symfony/symfony v3.2.0|install symfony/symfony v3.2.1|install symfony/symfony v3.2.2)",
        "package": {
            "name": "symfony/symfony",
            "version": "v3.1.1",
            /* ... rest of package info */
        },
        "target": {
            "name": "symfony/symfony",
            "version": "v3.2.2",
            /* ... rest of package info */
        }
    },
    /* ... more packages available for upgrade or install */
}
```

We have the following actions:
- `install` (providing keys: `reason`, `package`)
- `update` (providing keys: `reason`, `package`, `target`)
- `uninstall` (providing keys: `package`)

The key `package` is the "currently installed package" where the key `target` is the target version.
The reason is determining why a package is to be installed/upgraded/required at all.

**Comment by Toflar** [comment]
I don't see why this is needed to be honest? /cc @aschempp

**Comment by discordier** [comment]
To display the available version in the UI?
See the mockup screens, there is written the available version to which can be upgraded to.
In the end, this is essentially the contents of composer.lock prior installation with additional information.

**Comment by Toflar** [comment]
Yeah so it makes no sense for the cloud? You can just let it resolve and extract the information from the `composer.lock`?

**Comment by discordier** [comment]
I could but would have to scan the differences then on my own and will have no way to tell "cached" and will end up with less information (the rules would be missing i.e.).

In the end, I could construct the `composer.lock` from the information returned from these changes but not the other way around but I'll leave it up to you if it is needed (but don't complain to me again in the future if I don't supply information via tenside API which I only was able to retrieve via this "hack" :smile:)

**Comment by Toflar** [comment]
Okay, so I don't think it's needed for the resolver. We'll see though. Closing for now.
